language: java

jdk:
  - oraclejdk8
  
branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
  - rapatao@rapatao.com
  - dceschmidt@gmail.com
